- name: ID
  id: id
  visible: false
  placeholder:

- name: 项目编号
  id: projectCode
  span: 1
  placeholder: 请输入项目编号

- name: 项目名称
  id: projectName
  span: 1
  placeholder: 请输入项目名称

- name: 备注
  id: remark
  placeholder: 请输入备注信息